services:
  # A Docker web service
  - type: web
    name: langchain-demo
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && uvicorn main:app --host=0.0.0.0 --port=${PORT:-5000}
    envVars:
    - key: PYTHON_VERSION
      value: 3.10.12
    - key: LINE_CHANNEL_ACCESS_TOKEN
      sync: false
    - key: LINE_CHANNEL_SECRET
      sync: false
    - key: OPENAI_API_KEY
      sync: false
